In [1]:
import pandas as pd

df = pd.read_parquet("USD_60_indicators/STORJUSD_60.parquet")
df.head()

,timestamp,open,high,low,close,volume,trades,log_return,return,volume_change,...,ema_diff_norm_24_120,price_ema_diff_12,macd_hist,realized_vol_24,weighted_vol_24,volume_zscore_24,vwap_24,sto_osc_12,rsi,amihud_12
0,1594818000,0.19000,0.19000,0.18,0.18000,149.850896,3.0,-0.054067,-0.052632,NaN,...,0.000000,0.000000,0.000000,0.052632,0.052632,NaN,0.183333,0.000000,99.009901,0.000361
1,1594821600,0.19000,0.20900,0.18,0.18500,37359.559421,21.0,0.027399,0.027778,248.311552,...,0.001715,0.022869,0.000319,0.059512,0.027921,0.707107,0.191301,17.241379,100.000000,0.000181
2,1594825200,0.18000,0.18500,0.18,0.18500,8045.000000,15.0,0.000000,0.000000,-0.784660,...,0.003265,0.019351,0.000502,0.059512,0.025336,-0.364175,0.189894,17.241379,100.000000,0.000121
3,1594828800,0.18594,0.20990,0.18,0.18000,68886.414357,31.0,-0.027399,-0.027027,7.562637,...,0.003030,-0.006676,0.000269,0.065362,0.026367,1.288409,0.189938,0.000000,50.000000,0.000090
4,1594832400,0.18001,0.19776,0.18,0.19776,69008.784229,50.0,0.094097,0.098667,0.001776,...,0.008185,0.070848,0.001240,0.118352,0.063998,0.992985,0.190653,59.397993,81.988473,0.000073

In [2]:
df.info()
df.describe()
df.sample(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41291 entries, 0 to 41290
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   timestamp             41291 non-null  int64
 1   open                  39469 non-null  float64
 2   high                  36264 non-null  float64
 3   low                   36264 non-null  float64
 4   close                 39469 non-null  float64
 5   volume                36264 non-null  float64
 6   trades                36264 non-null  float64
 7   log_return            39469 non-null  float64
 8   return                39469 non-null  float64
 9   volume_change         36263 non-null  float64
 10  close_to_high         36264 non-null  float64
 11  close_to_low          36264 non-null  float64
 12  log_price_range       36264 non-null  float64
 13  ma_zscore_12          39464 non-null  float64
 14  mom_24_4              38010 non-null  float64
 15  mom_168_24            37784 non-null  float64
 16  strev_24              37971 non-null  float64
 17  ltrev_168             37779 non-null  float64
 18  ema_diff_norm_12_48   39469 non-null  float64
 19  ema_diff_norm_24_120  39469 non-null  float64
 20  price_ema_diff_12     39469 non-null  float64
 21  macd_hist             41291 non-null  float64
 22  realized_vol_24       41291 non-null  float64
 23  weighted_vol_24       41291 non-null  float64
 24  volume_zscore_24      36263 non-null  float64
 25  vwap_24               41291 non-null  float64
 26  sto_osc_12            39493 non-null  float64
 27  rsi                   39469 non-null  float64
 28  amihud_12             41288 non-null  float64
dtypes: float64(28), int64(1)
memory usage: 9.1 MB

,timestamp,open,high,low,close,volume,trades,log_return,return,volume_change,...,ema_diff_norm_24_120,price_ema_diff_12,macd_hist,realized_vol_24,weighted_vol_24,volume_zscore_24,vwap_24,sto_osc_12,rsi,amihud_12
33315,1714752000,0.53512,0.53755,0.53512,0.53724,5644.519231,7.0,0.008824,0.008864,2.934029,...,0.006082,0.014576,0.000400,0.044965,0.009598,0.344274,0.530570,92.372204,54.700038,5.240604e-05
8280,1624626000,0.63028,0.64168,0.62459,0.64168,14630.887810,9.0,0.026786,0.027148,-0.428089,...,-0.047124,-0.014010,-0.005897,0.063331,0.012834,0.334852,0.661312,24.739433,32.306720,1.529735e-05
24503,1683028800,0.33800,0.34000,0.33786,0.33889,1970.424211,19.0,0.002630,0.002633,5656.338902,...,-0.031174,0.002933,0.000586,0.018813,0.006591,-0.075729,0.337449,72.388060,44.639556,6.323588e-06
38178,1732258800,0.51264,0.51264,0.50893,0.50893,339.164392,6.0,-0.007263,-0.007237,-0.983459,...,0.011711,0.005252,0.000822,0.042784,0.007526,-0.870855,0.503122,50.515971,66.852174,5.363774e-06
25247,1685707200,0.30053,0.30064,0.29951,0.29988,1745.266528,38.0,-0.001899,-0.001897,0.089942,...,-0.001564,0.002156,0.000273,0.015399,0.002469,-0.644075,0.297923,79.356568,65.965233,9.535228e-07
16172,1653037200,0.55662,0.56297,0.55662,0.56041,577.906773,8.0,0.005188,0.005202,-0.405171,...,-0.001856,0.010818,0.000554,0.074556,0.016446,-0.673481,0.553164,79.135277,61.866869,2.333848e-05
2231,1602849600,0.43602,0.43948,0.43602,0.43917,2239.121284,6.0,-0.001888,-0.001886,-0.173619,...,-0.147463,-0.008685,0.000999,0.102901,0.029666,-0.748017,0.471272,27.347611,34.911843,3.598786e-05
34877,1720375200,0.33496,0.33496,0.33496,0.33496,100.000000,1.0,-0.004825,-0.004813,-0.983524,...,-0.012604,-0.003878,-0.000901,0.033026,0.006427,-0.436678,0.338822,30.246914,49.018257,4.097141e-05
3889,1608818400,0.28966,0.28967,0.28966,0.28966,10563.879817,9.0,-0.005371,-0.005357,14.568104,...,-0.133349,0.028005,0.003825,0.118879,0.034716,0.034350,0.287715,95.000000,58.643429,1.099831e-05
4276,1610211600,0.41397,0.42596,0.40860,0.42340,17578.872271,30.0,0.021003,0.021225,218.049674,...,0.086253,0.052303,0.004882,0.134537,0.033563,-0.220251,0.375211,88.304898,70.684535,3.231748e-05

In [3]:
df.to_csv("STORJUSD_60.csv", index=False)